version: "3.9"

services:
  db:
    container_name: db_api_kenzie_food
    image: postgres:12
    ports:
      - 5433:5433
    environment: 
      - POSTGRES_USER=process.env.POSTGRES_USER
      - POSTGRES_PASSWORD=process.env.POSTGRES_PASSWORD
      - POSTGRES_DB=process.env.POSTGRES_DB
      
  api_kenzie_food:
    build: 
      context: ./
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    expose:
     - '3000'
    depends_on: 
      - db
